// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jjjxrvndulrqaamnexcs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impqanhydm5kdWxycWFhbW5leGNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyODI1MjcsImV4cCI6MjA3MTg1ODUyN30.siUHIGm0Wv1nc5qCXH4T-XkCJuuDrDNOxTd7pG1I5F8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});